#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by skill-auto-installer
# Installs the "human-readable-tech-doc" skill to ~/.claude/skills/human-readable-tech-doc/

SKILL_DIR="$HOME/.claude/skills/human-readable-tech-doc"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/human-readable-tech-doc"

echo "Installing human-readable-tech-doc..."

# Create directory structure
mkdir -p "$SKILL_DIR/references"

# Download files
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/references/patterns.md" -o "$SKILL_DIR/references/patterns.md"
curl -fsSL "$REPO_BASE/references/diataxis-cheatsheet.md" -o "$SKILL_DIR/references/diataxis-cheatsheet.md"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

# Verify YAML frontmatter exists
if ! head -1 "$SKILL_DIR/SKILL.md" | grep -q "^---"; then
  echo "ERROR: Installation failed - SKILL.md has invalid frontmatter"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "human-readable-tech-doc installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  Trigger:  When asked to write, generate, or improve technical documentation"
echo "  To uninstall: rm -rf $SKILL_DIR"
