#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "clash-party-safe-update" skill to ~/.claude/skills/clash-party-safe-update/

SKILL_DIR="$HOME/.claude/skills/clash-party-safe-update"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/clash-party-safe-update"

echo "Installing clash-party-safe-update..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/references"
mkdir -p "$SKILL_DIR/scripts"

# Download files
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/references/stability-plan.md" -o "$SKILL_DIR/references/stability-plan.md"
curl -fsSL "$REPO_BASE/references/windows-tun.md" -o "$SKILL_DIR/references/windows-tun.md"
curl -fsSL "$REPO_BASE/scripts/check-agent-log.py" -o "$SKILL_DIR/scripts/check-agent-log.py"
curl -fsSL "$REPO_BASE/scripts/check-reload.py" -o "$SKILL_DIR/scripts/check-reload.py"
curl -fsSL "$REPO_BASE/scripts/inspect-network.ps1" -o "$SKILL_DIR/scripts/inspect-network.ps1"
curl -fsSL "$REPO_BASE/scripts/safety-check.sh" -o "$SKILL_DIR/scripts/safety-check.sh"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "clash-party-safe-update installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
