#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "dsh-worker-review" skill to ~/.claude/skills/dsh-worker-review/

SKILL_DIR="$HOME/.claude/skills/dsh-worker-review"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/dsh-worker-review"

echo "Installing dsh-worker-review..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/references"
mkdir -p "$SKILL_DIR/scripts"

# Download files
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/references/setup.md" -o "$SKILL_DIR/references/setup.md"
curl -fsSL "$REPO_BASE/scripts/run_worker.py" -o "$SKILL_DIR/scripts/run_worker.py"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "dsh-worker-review installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
