#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "alpha-research-recorder" skill to ~/.claude/skills/alpha-research-recorder/

SKILL_DIR="$HOME/.claude/skills/alpha-research-recorder"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/alpha-research-recorder"

echo "Installing alpha-research-recorder..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/templates"

# Download files
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/templates/final_summary.md.template" -o "$SKILL_DIR/templates/final_summary.md.template"
curl -fsSL "$REPO_BASE/templates/round_NNNN.yml.template" -o "$SKILL_DIR/templates/round_NNNN.yml.template"
curl -fsSL "$REPO_BASE/templates/session_metadata.yml.template" -o "$SKILL_DIR/templates/session_metadata.yml.template"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "alpha-research-recorder installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
