#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "learn-codebase" skill to ~/.claude/skills/learn-codebase/

SKILL_DIR="$HOME/.claude/skills/learn-codebase"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/learn-codebase"

echo "Installing learn-codebase..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/references"
mkdir -p "$SKILL_DIR/assets"

# Download files
curl -fsSL "$REPO_BASE/LICENSE" -o "$SKILL_DIR/LICENSE"
curl -fsSL "$REPO_BASE/references/QUESTION-PATTERNS.md" -o "$SKILL_DIR/references/QUESTION-PATTERNS.md"
curl -fsSL "$REPO_BASE/references/JOURNAL-TEMPLATE.md" -o "$SKILL_DIR/references/JOURNAL-TEMPLATE.md"
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/assets/logo-icon.svg" -o "$SKILL_DIR/assets/logo-icon.svg"
curl -fsSL "$REPO_BASE/assets/icon.svg" -o "$SKILL_DIR/assets/icon.svg"
curl -fsSL "$REPO_BASE/assets/logo-dark.svg" -o "$SKILL_DIR/assets/logo-dark.svg"
curl -fsSL "$REPO_BASE/assets/logo-light.svg" -o "$SKILL_DIR/assets/logo-light.svg"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "learn-codebase installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
