#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "mining-factors" skill to ~/.claude/skills/mining-factors/

SKILL_DIR="$HOME/.claude/skills/mining-factors"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/mining-factors"

echo "Installing mining-factors..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/agents"
mkdir -p "$SKILL_DIR/references"

# Download files
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/agents/openai.yaml" -o "$SKILL_DIR/agents/openai.yaml"
curl -fsSL "$REPO_BASE/references/research-lessons.md" -o "$SKILL_DIR/references/research-lessons.md"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "mining-factors installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
