#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "route-longmemory" skill to ~/.claude/skills/route-longmemory/

SKILL_DIR="$HOME/.claude/skills/route-longmemory"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/route-longmemory"

echo "Installing route-longmemory..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/agents"
mkdir -p "$SKILL_DIR/references"

# Download files
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/agents/openai.yaml" -o "$SKILL_DIR/agents/openai.yaml"
curl -fsSL "$REPO_BASE/references/tool-contract.md" -o "$SKILL_DIR/references/tool-contract.md"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "route-longmemory installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
