#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "mainline-drift-audit" skill to ~/.claude/skills/mainline-drift-audit/

SKILL_DIR="$HOME/.claude/skills/mainline-drift-audit"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/mainline-drift-audit"

echo "Installing mainline-drift-audit..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/agents"
mkdir -p "$SKILL_DIR/scripts"

# Download files
curl -fsSL "$REPO_BASE/agents/openai.yaml" -o "$SKILL_DIR/agents/openai.yaml"
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/scripts/scan_repo.py" -o "$SKILL_DIR/scripts/scan_repo.py"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "mainline-drift-audit installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
